### ISSUE TITLE
Periodic Nuitrack license timeout

### ISSUE THREAD

**Issue by RMichaelSwan** [luxai-qtrobot/QA#17]
When running the Nuitrack face recognition demo, the license periodically times out and then the process is restarted (receive the error: "Nuitrack license timeout"). It seems to occur after 30 seconds to 1 minute and at least one or two face acquisitions and losses. Is there any way to keep this from occurring? The restart obviously causes all tracks to be lost and causes the face recognition app to lock for ~10 seconds while the process restarts which is not acceptable for my use case.

**Comment by apaikan** [comment]
Hi @RMichaelSwan 
It seems your nuitrack is running with trial licences which restart itself every few minutes. I will send you the proper licence and the installation guide by email
