### ISSUE TITLE
tablet can't connect

### ISSUE THREAD

**Issue by andrewpbstout** [luxai-qtrobot/QA#22]
I've been using the tablet that came with QTrobot, with LuxAI's app, to develop and present quick demos. Today it stopped working due to some kind of a connection issue. I've power-cycled both robot and tablet, and I logged out of the robot in the LuxAI app. Now I can't log back in: I get an error that says "Connection isueeee, please try again later!"

This worked out of the box when I got it, so I've never had to do any setup; I'm using the same username and password I use to ssh.

How can I recover the connection between tablet and robot?

**Comment by codionysus** [comment]
Username and password to login in LuxAI app in the tablet is not the same as ssh. With your QTrobot you have also received username and password for your tablets. When attempting to login in LuxAI app you need to be connected to the internet and after that you can switch to QTrobot wifi. Can you contact us on development@luxai.com
