### ISSUE TITLE
IP connection

### ISSUE THREAD

**Issue by abouttier** [luxai-qtrobot/QA#23]
Hello,
I have a connection problem with the QTROBOT IP 192.168.100.1
It asks me for a private connection with user and password.
If I enter the WIFI credentials or USER credentials for tablet, nothing works.
Did I miss a stage?
![IP connection](https://user-images.githubusercontent.com/60920690/74227966-d557ff80-4cbf-11ea-9df8-9f18cabe24c0.PNG)

**Comment by codionysus** [comment]
Can you please contact us on development@luxai.com so that we can share login credentials with you.
