### ISSUE TITLE
QTRobot hotspot undetected or unstable

### ISSUE THREAD

**Issue by PatWg** [luxai-qtrobot/QA#40]
The QTRobot hotspot is not shown in the list of available networks. When it is, the connection seems to be quite unstable and I cannot SSH into qtrobot.

How can I troubleshoot this issue?

**Comment by codionysus** [comment]
Hi @PatWg, Can you please contact us at development@luxai.com

**Comment by PatWg** [comment]
Hi @dkcodeguy, thanks for the message. Email has been sent.
