### ISSUE TITLE
qt_robot.inc reference to melodic, but noetic installed. 

### ISSUE THREAD

**Issue by TechnoX** [luxai-qtrobot/QA#46]
On my robot the qt_robot.inc file has not been updated in the NUC. 

I get the following error: 
/home/qtrobot/robot/autostart/qt_robot.inc: line 70: /opt/ros/melodic/setup.bash: No such file or directory

I have updated it to Noetic on my robot, but just wanted you to know this so you can update in your repos or internal files.

**Comment by codionysus** [comment]
Hi @TechnoX, 
thanks for letting us know. This was fixed.
