### ISSUE TITLE
QTRP user developer or qtrobot

### ISSUE THREAD

**Issue by sulibo** [luxai-qtrobot/QA#51]
In the newer version of QTrobot, QTRP is accessed from QTPC via ssh under the username developer instead of qtrobot. However, the auto start scripts and tutorials (for example [this one](https://github.com/luxai-qtrobot/software/blob/master/apps/qt_respeaker_app/autostart/start_qt_respeaker_app.sh)) are still based on the username qtrobot. Is it possible to update the relevant documents? Thanks!

**Comment by codionysus** [comment]
Hi @sulibo,
Everything that is running on the QTRP should be running under username 'qtrobot'. User 'developer' is just for ssh access, if you need to develop or change something you can use 'qtrobot' user. You can find more tutorials and tips on how to use QTrobot in our [documentation](https://docs.luxai.com/).

**Comment by sulibo** [comment]
Hi @dkcodeguy, 
Thanks for the swift reply. Okay, I see. I assume the password for 'qtrobot' is the same as 'developer'.

**Comment by codionysus** [comment]
HI @sulibo,
Password for 'qtrobot' is always 'qtrobot'. If you change password of developer user that doesn't change qtrobot user.

**Comment by sulibo** [comment]
Thanks. I failed to log in use 'qtrobot' as the password for the user 'qtrobot'. Probably, it was changed by my colleagues. I change it back and it works now. 

Anyway, it would be nice to mention that 'developer' is only used for access in your documentation. One should switch to 'qtrobot' if she/he wants to develop or change something.
